services:
  - type: web
    runtime: node
    name: ksp-system-pir32112122
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DISCORD_CLIENT_ID
        value: "1526962966975610991"
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_GUILD_ID
        value: "1527014315381751928"
      - key: DISCORD_ROLE_ID
        value: "1527014315411116062"
      - key: SESSION_SECRET
        generateValue: true
